const WORKS = [
  {
    id: 1,
    title: "Thailand Shopper",
    category: ["explainer"],
    thumbnail: "https://img.youtube.com/vi/plyQNjPd4YU/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/plyQNjPd4YU",
    description: "Explainer Video",
    year: 2024,
    featured: true,
  },
  {
    id: 2,
    title: "JobGlance",
    category: ["uxui"],
    thumbnail: "https://img.youtube.com/vi/5G7O3uuTeMA/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/5G7O3uuTeMA",
    description: "App Presentation",
    year: 2024,
    featured: true,
  },
  {
    id: 3,
    title: "FloraRose",
    category: ["uxui"],
    thumbnail: "https://img.youtube.com/vi/dLH2WMt0C48/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/dLH2WMt0C48",
    description: "App Demo Presentation",
    year: 2024,
    featured: true,
  },
  {
    id: 4,
    title: "Mamori Cybersecurity",
    category: ["explainer"],
    thumbnail: "https://img.youtube.com/vi/-BEcmSmywe4/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/-BEcmSmywe4",
    description: "Explainer Video for Cybersecurity Company",
    year: 2024,
    featured: true,
  },
  {
    id: 5,
    title: "Easy Elders",
    category: ["uxui"],
    thumbnail: "https://img.youtube.com/vi/5T-BQNxXnOU/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/5T-BQNxXnOU",
    description: "App Demo Presentation",
    year: 2024,
    featured: true,
  },
  {
    id: 6,
    title: "ZenMarket",
    category: ["explainer"],
    thumbnail: "https://img.youtube.com/vi/L_G1qJAFicA/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/L_G1qJAFicA",
    description: "Explainer Video for ZenMarket",
    year: 2024,
    featured: true,
  },
  {
    id: 7,
    title: "Half Tennis",
    category: ["explainer", "character"],
    thumbnail: "https://img.youtube.com/vi/vdql8y0Vu8k/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/vdql8y0Vu8k",
    description: "Promo video for Half Tennis",
    year: 2024,
    featured: true,
  },
  {
    id: 8,
    title: "TouchMe",
    category: ["uxui"],
    thumbnail: "https://img.youtube.com/vi/nlH4YIrgmOw/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/nlH4YIrgmOw",
    description: "Promo video for TouchMe",
    year: 2024,
    featured: true,
  },
  {
    id: 9,
    title: "HEINE",
    category: ["typography"],
    thumbnail: "https://img.youtube.com/vi/UwdBFw_CY5w/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/UwdBFw_CY5w",
    description: "Promo video for HEINE",
    year: 2024,
    featured: true,
  },
  {
    id: 10,
    title: "LPG Knowledge",
    category: ["explainer"],
    thumbnail: "https://img.youtube.com/vi/_Ce3PLgU5Wc/maxresdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/_Ce3PLgU5Wc",
    description: "Educational Explainer Video for Department of Energy Business, Thailand",
    year: 2024,
    featured: true,
  },
];

const GRAPHIC_WORKS = [
  {
    id: "g1",
    title: "Tom Yum Kung Noodles",
    category: ["illustration", "animation"],
    thumbnail: "assets/graphic/noodle-ezgif.com-optimize.gif",
    images: ["assets/graphic/noodle-ezgif.com-optimize.gif"],
    what: "Illustration & Short Animation",
    concept: "Tom Yum Kung Noodles served in a retro microwave — blending Thai flavor with Japanese street-food aesthetics. Bold graphic style mixing flat illustration, Y2K/risograph textures, and anime-inspired typography.",
    client: "Personal Project",
    year: 2023,
  },
  {
    id: "g2",
    title: "Fintech App Ecosystem",
    category: ["illustration", "animation"],
    thumbnail: "assets/graphic/isoPhone.png",
    images: ["assets/graphic/isoPhone.png"],
    what: "Isometric Illustration & Loop Animation",
    concept: "An isometric exploded-view of a mobile trading/fintech app ecosystem — showing the invisible infrastructure behind a phone screen: blockchain nodes, marketplace, security layer, buy/sell mechanics. Designed to loop as a web hero illustration, making complex tech feel approachable and visually satisfying.",
    client: "Personal Project",
    year: 2024,
  },  {
    id: "g3",
    title: "Happy New Year 2026",
    category: ["illustration", "editorial"],
    thumbnail: "assets/graphic/2026greetingCard.png",
    images: ["assets/graphic/2026greetingCard.png"],
    what: "New Year Greeting Card Design",
    concept: "A tarot-card style New Year greeting for 2026 — Year of the Horse. Illustrated in a flat, editorial style with bold colors (blue, pink, gold) and vintage card typography. The horse character is cheerful and stylized, framed by an arch and sunburst rays reminiscent of classic tarot card composition.",
    client: "Personal Project",
    year: 2025,
  },];

const TESTIMONIALS = [
  {
    name: "คุณมินท์",
    role: "Marketing Manager, BrandX",
    text: "งานออกมาสวยมาก ตรงกับ brief เลย ทีมชอบมาก ส่งงานตรงเวลาด้วย ประทับใจมากค่ะ",
    avatar: "🌸",
  },
  {
    name: "คุณโฟม",
    role: "Founder, CosmeticTH",
    text: "ดูแลงานดี ใส่ใจในรายละเอียด คุยง่าย revise ได้ตามต้องการ แนะนำให้ทุกคนเลยค่ะ",
    avatar: "✨",
  },
  {
    name: "คุณบีม",
    role: "Content Creator",
    text: "ผลงาน motion ดูโปรมาก แต่ราคาสมเหตุสมผล ทำงานร่วมกันได้สนุกมาก",
    avatar: "🎬",
  },
  {
    name: "คุณเฟิร์น",
    role: "Product Owner, AppStartup",
    text: "ทำ UX presentation ออกมาดูดีมาก ลูกค้าประทับใจ ได้ funding รอบนี้ ขอบคุณมากนะคะ",
    avatar: "💜",
  },
  {
    name: "คุณแนน",
    role: "Art Director, Agency",
    text: "Animation smooth มาก timing ดีเยี่ยม professional มากค่ะ จะกลับมาจ้างอีกแน่นอน",
    avatar: "🎨",
  },
  {
    name: "คุณต้น",
    role: "CEO, E-commerce Brand",
    text: "คุณภาพงานเกินราคามาก revise ให้ตลอด ไม่เบื่อ ขยันและรับผิดชอบมาก",
    avatar: "⭐",
  },
];

const HEADER_FRAMES = [
  { src: null, label: "Explainer Video", color: "#FFD6E7" },
  { src: null, label: "Typography Animation", color: "#E8D5F5" },
  { src: null, label: "Character Animation", color: "#D5E8F5" },
  { src: null, label: "UX/UI Presentation", color: "#F5F0D5" },
];

const CONTACT = {
  email: "smallpaws.motion@gmail.com",
  instagram: "@smallpaws.motion",
  facebook: "smallpaws.motion",
  tiktok: "@smallpaws.motion",
};